resorts_list = [('Copper Mountain', 'copper+mountain'),
                ('Winter Park', 'winter+park'),
                ('Breckenridge', 'breckenridge'),
                ('Arapahoe Basin', 'arapahoe+basin'),
                ('Wolf Creek', 'wolf+creek'),
                ('Vail', 'vail'),
                ('Steven\'s Pass', 'stevens+pass'),
                ('Whistler Blackcomb', 'whistler+blackcomb'),
                ('Telluride', 'telluride'),
                ('Beaver Creek', 'beaver+creek'),
                ('Mammoth Mountain', 'mammoth+mountain'),
                ('Aspen Snowmass', 'aspen+snowmass'),
                ('Sun Peaks', 'sun+peaks'),
                ('Lake Louise', 'lake+louise'),
                ('Keystone', 'keystone'),
                ('Big White', 'big+white'),
                ('Mont Sainte Anne', 'mont+sainte+anne'),
                ('Stowe', 'stowe'),
                ('Heavenly', 'heavenly'),
                ('Silver Star', 'silver+star'),
                ('Fernie', 'fernie'),
                ('Squaw Valley', 'squaw+valley'),
                ('Sunshine Village', 'sunshine+village'),
                ('Panorama', 'panorama'),
                ('Steamboat Springs', 'steamboat'),
                ('Kicking Horse', 'kicking+horse'),
                ('Big Sky', 'big+sky'),
                ('Alta', 'alta'),
                ('Revelstoke', 'revelstoke'),
                ('Nakiska', 'nakiska'),
                ('Deer Valley', 'deer+valley'),
                ('Jackson Hole', 'jackson+hole'),
                ('Crested Butte', 'crested+butte'),
                ('Powder Mountain', 'powder+mountain'),
                ('Whiteface', 'whiteface'),
                ('Mt. Bachelor', 'mt+bachelor'),
                ('Northstar California', 'northstar'),
                ('Sugarloaf', 'sugarloaf'),
                ('Le Massif de Charlevoix', 'le+massif+de+charlevoix'),
                ('Snowbird', 'snowbird'),
                ('Sun Valley', 'sun+valley'),
                ('Mt. Hood Meadows', 'mt+hood+meadows'),
                ]
